apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-plug-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: smart-plug-server
      labels:
        app: smart-plug-server
    spec:
      containers:
        - name: smart-plug-server-container
          image: smartplug.azurecr.io/smart-plug-server-dev:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: smart-plug-server-configmap
        - name: mosquitto-container
          image: eclipse-mosquitto:2.0
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: mosquitto-data
              mountPath: /mosquitto/data
            - name: mosquitto-log
              mountPath: /mosquitto/log
            - name: config-file
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: password-file
              mountPath: /mosquitto/config/passwd
              subPath: passwd
      imagePullSecrets:
        - name: acr-secret
      volumes:
        - name: config-file
          configMap:
            name: mosquitto-config   
        - name: mosquitto-data
          emptyDir: {}
        - name: mosquitto-log
          emptyDir: {}
        - name: password-file
          configMap:
            name: mosquitto-passwords
  selector:
    matchLabels:
      app: smart-plug-server