apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-plug-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: smart-plug-server
      labels:
        app: smart-plug-server
    spec:
      containers:
        - name: smart-plug-server-container
          image: smartplug.azurecr.io/smart-plug-server-dev:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: smart-plug-server-configmap
      imagePullSecrets:
        - name: acr-secret
  selector:
    matchLabels:
      app: smart-plug-server